### ISSUE TITLE
[Frontend] Fix create post form

### ISSUE THREAD

**Issue by dilaragokay** [bounswe/bounswe2018group4#112]
* Inline multimedia
* Time
* Location

**Comment by dilaragokay** [comment]
We accomplished to add inline multimedia to our memories! The procedure for inline multimedia is explained in #101. The most recent changes in create-memory-material do not have time and location information yet.

**Comment by ege-saygili-2015405147** [comment]
Backend will send and receive time with following fields:

* type --> will define the format
d for Decade only
y for Year only
ym for Year-Month
ymd for Year-Month-Day
full for Year - Month - Day - Hour - Minute
* dateString --> contains the date as a string

An example for century: 1970s
An example for year: 1983
An example for year-month: April 2017
An example for year-month-day: 11 May 2003
An example for year-month-day-hour-minute: 2 August 1996 21:18   

Is this format OK for Frontend?

**Comment by ege-saygili-2015405147** [comment]
Update: Since we will also have time periods as well as single times, we made some changes.

* type --> 0 for single time, 1 for time period
* format --> will define the format
d for Decade only
y for Year only
ym for Year-Month
ymd for Year-Month-Day
full for Year - Month - Day - Hour - Minute
* dateString1 --> contains the date as a string
* dateString2 --> optional, will be empty for single time

**Comment by ege-saygili-2015405147** [comment]
Update: We fixed the field names.
date_type
date_format
date_string1
date_string2

**Comment by dilaragokay** [comment]
Is there any specification about how date_string1 and date_string2 should be?

**Comment by dilaragokay** [comment]
Location is being handled by Büşra at #158. Time is added at #186

**Comment by dilaragokay** [comment]
All done!
